version: '3'

services:
  app:
    container_name: main_app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_ID=${USER_ID}
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: 'python3 /project/scraper.py -f'
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - project-network
  db:
    container_name: mongo_db
    image: mongo:3.6-stretch
    volumes:
      - ./data/mongo:/data/db
    env_file:
      - ./.env
    ports:
      - ${MONGO_DB_PORT}:${MONGO_DB_PORT}
    networks:
      - project-network

networks:
  project-network:
    driver: bridge
