version: '3'

services:
  app:
    container_name: main_app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_ID=${USER_ID}
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: on-failure
    command: 'python3 /code/scraper.py'
    env_file:
      - ./.env
    links:
      - db:mongodb
    depends_on:
      - db
    networks:
      - project-network
  db:
    container_name: mongo_db
    image: mongo:3.6-stretch
    env_file:
      - ./.env
    ports:
      - ${MONGO_DB_PORT}:${MONGO_DB_PORT}
    networks:
      - project-network

networks:
  project-network:
