version: 2
jobs:
  build:
    working_directory: /project
    docker:
      - image: circleci/python:3.7
        enviroment:
          PYTHONUNBUFFERED: 1
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=python-circleci-docker' >> $BASH_ENV
            virtualenv venv
            . venv/bin/activate
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . helloworld/bin/activate
            python -m unittest discover -s ./tests/
